/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyTitle {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLMyTitleElement extends Components.MyTitle, HTMLStencilElement {
    }
    var HTMLMyTitleElement: {
        prototype: HTMLMyTitleElement;
        new (): HTMLMyTitleElement;
    };
    interface HTMLElementTagNameMap {
        "my-title": HTMLMyTitleElement;
    }
}
declare namespace LocalJSX {
    interface MyTitle {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "my-title": MyTitle;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-title": LocalJSX.MyTitle & JSXBase.HTMLAttributes<HTMLMyTitleElement>;
        }
    }
}
